#!/bin/sh
buildFile=target/currentBuild.txt

if [ -a "$buildFile" ]
  then
  currentBuild=$(cat "$buildFile")

  if [ "$currentBuild" != "" ]
   then
    git tag "$currentBuild"
    echo "Last commit tagged with buildTime = $currentBuild"
    echo "" > buildFile
    exit 0
  fi
  echo "currentBuild is empty, skip commit tagging"
  exit 0
fi

echo "target/currentBuild.txt not found"